-- AlterTable
ALTER TABLE "EndPoints" ADD COLUMN     "interval" INTEGER,
ADD COLUMN     "lastPing" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "nextPing" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;
